import Link from "next/link";
import { BodyExplorer } from "@/components/BodyExplorer";
import { BookingAction } from "@/components/BookingAction";
import { CareRows } from "@/components/CareRows";
import { FaqList } from "@/components/FaqList";

export default function Home() {
  return <>
    <section className="hero shell"><div className="hero-inner"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star" aria-hidden="true">✳</span> 신매역 · 알지 이비인후과</p><h1>귀 기울이고,<br /><em>함께 이해하는</em><br />진료.</h1><p className="hero-description">귀·코·목의 불편함을 이야기하고, 필요한 진료 안내를 차분히 살펴보세요.</p><div className="hero-actions"><a href="#explore" className="primary-link">진료 부위 살펴보기 <span aria-hidden="true">↘</span></a><BookingAction /></div></div><div className="hero-art" aria-hidden="true"><div className="hero-art-ring ring-one" /><div className="hero-art-ring ring-two" /><div className="hero-art-ring ring-three" /><div className="hero-art-center">알<span>지</span></div><span className="art-caption">HEAR · BREATHE · SPEAK</span></div></div><div className="hero-bottom"><span>귀 / 코 / 목</span><span>만성·알레르기 비염　/　난청·이명　/　암</span><span>SCROLL TO EXPLORE ↓</span></div></section>
    <section id="explore" className="explore-section section-pad"><div className="shell"><div className="section-heading"><div><p className="eyebrow">EXPLORE CARE <span>01 / 04</span></p><h2>어디가<br /><em>불편하신가요?</em></h2></div><p>머리·목 그림의 부위를 선택하면<br />관련 진료 안내를 볼 수 있습니다.</p></div><BodyExplorer /></div></section>
    <section className="care-section section-pad"><div className="shell"><div className="section-heading"><div><p className="eyebrow">FOCUS AREAS <span>02 / 04</span></p><h2>한 사람의 일상에서<br /><em>시작하는 진료.</em></h2></div><p>알지 이비인후과의 중점 진료를<br />살펴보세요.</p></div><CareRows /><p className="care-note">‘암’은 머리·목 부위의 암과 종양(두경부 종양)에 관한 안내입니다.</p></div></section>
    <section className="philosophy-section section-pad"><div className="shell philosophy-grid"><div><p className="eyebrow">OUR APPROACH <span>03 / 04</span></p><div className="philosophy-mark" aria-hidden="true">“</div></div><div><h2>설명은<br />진료의 일부입니다.</h2><p>알지 이비인후과가 지향하는 진료 방향을 소개합니다. 실제 의료진 소개와 진료 과정은 확인된 자료가 준비되면 더 자세히 전하겠습니다.</p><Link className="text-link" href="/about">병원소개 살펴보기 <span aria-hidden="true">↗</span></Link></div></div></section>
    <section className="practical-section section-pad"><div className="shell"><div className="section-heading"><div><p className="eyebrow">PLAN YOUR VISIT <span>04 / 04</span></p><h2>방문 전에<br /><em>확인하세요.</em></h2></div></div><div className="practical-grid"><div className="practical-item"><span className="practical-icon" aria-hidden="true">⌖</span><h3>신매역 인근</h3><p>정확한 주소와 교통·주차 정보는 확인 후 안내합니다.</p><Link href="/visit" className="text-link">이용안내 <span aria-hidden="true">↗</span></Link></div><div className="practical-item"><span className="practical-icon" aria-hidden="true">◷</span><h3>진료 일정</h3><p>진료 시간과 휴진 일정은 확정 후 게시합니다.</p><Link href="/visit" className="text-link">방문 정보 <span aria-hidden="true">↗</span></Link></div><div className="practical-item"><span className="practical-icon" aria-hidden="true">↗</span><h3>네이버 예약</h3><p>예약 링크가 준비되면 이곳에서 안내합니다.</p><BookingAction compact /></div></div><div className="home-faq"><div><p className="eyebrow">COMMON QUESTIONS</p><h3>자주 묻는 질문</h3><Link href="/faq" className="text-link">전체 보기 <span aria-hidden="true">↗</span></Link></div><FaqList limit={3} /></div></div></section>
  </>;
}
